#!/bin/bash
killall -q conky
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done
conky --daemonize --pause=3 --quiet -c ~/.config/conky/conkysystem.conf &&
conky --daemonize --pause=3 --quiet -c ~/.config/conky/conkyport.conf &&
conky --daemonize --pause=3 --quiet -c ~/.config/conky/conkyhotkey.conf &&
conky --daemonize --pause=3 --quiet -c ~/.config/conky/conkybar.conf &&
exit 0
